In [ ]:
!pip install -U scikit-learn

     |████████████████████████████████| 6.8MB 2.7MB/s 
  Found existing installation: scikit-learn 0.22.2.post1
    Uninstalling scikit-learn-0.22.2.post1:
      Successfully uninstalled scikit-learn-0.22.2.post1


In [ ]:
#Importing Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import re
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.metrics import mutual_info_score
from sklearn.neighbors import NearestNeighbors
from sklearn.preprocessing import scale
from sklearn.utils import check_random_state
from sklearn.utils.fixes import _astype_copy_false
from sklearn.utils.validation import check_array, check_X_y
from sklearn.utils.validation import _deprecate_positional_args
from sklearn.utils.multiclass import check_classification_targets
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import confusion_matrix
from sklearn import svm
from scipy import special, stats
from scipy.sparse import issparse
from sklearn.base import BaseEstimator
from sklearn.preprocessing import LabelBinarizer
from sklearn.utils import (as_float_array, check_array, check_X_y, safe_sqr,safe_mask)
from sklearn.utils.extmath import safe_sparse_dot, row_norms
from sklearn.utils.validation import check_is_fitted
from sklearn.utils.validation import _deprecate_positional_args
from sklearn.feature_selection._base import SelectorMixin
from sklearn.metrics import roc_auc_score
from scipy.sparse import issparse
from scipy.special import digamma
import scipy.stats as stats
from subprocess import check_output
#from mlxtend.feature_selection import SequentialFeatureSelector as SFS
import warnings
warnings.filterwarnings('ignore')
%matplotlib inline

In [ ]:
#importing dataset
df = pd.read_csv('DLBCL.tab', delimiter='\t')
df.shape

(79, 7071)

In [ ]:
df.head()

A28102 AB000114_at AB000115_at  ... M71243_f_at Z78285_f_at     class
0  continuous  continuous  continuous  ...  continuous  continuous  DLBCL FL
1         NaN         NaN         NaN  ...         NaN         NaN     class
2          -1         -45         176  ...          76         -28     DLBCL
3          25         -17         531  ...          41         -45     DLBCL
4          73          91         257  ...         164         -62     DLBCL

[5 rows x 7071 columns]

In [ ]:
df=df.dropna().loc[1:,:]

In [ ]:
X = df.drop(['class'], axis=1)
X.head()

A28102 AB000114_at AB000115_at  ... L49218_f_at M71243_f_at Z78285_f_at
2     -1         -45         176  ...           3          76         -28
3     25         -17         531  ...          -4          41         -45
4     73          91         257  ...          38         164         -62
5    267          41         202  ...         -63          73         -13
6     16          24         187  ...          15         155         -26

[5 rows x 7070 columns]

In [ ]:
# Mapping classes into integers
y = df['class']
y=y.map({'DLBCL': 1, 'FL': 0})
y.head()

2    1
3    1
4    1
5    1
6    1
Name: class, dtype: int64

In [ ]:
df.dtypes

A28102         object
AB000114_at    object
AB000115_at    object
AB000220_at    object
AB000409_at    object
                ...  
Z17240_at      object
L49218_f_at    object
M71243_f_at    object
Z78285_f_at    object
class          object
Length: 7071, dtype: object

In [ ]:
print(X.shape)
print(y.shape)

(77, 7070)
(77,)


In [ ]:
#Train test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=101)
X_train.shape, y_train.shape, X_test.shape, y_test.shape

((61, 7070), (61,), (16, 7070), (16,))

In [ ]:
from sklearn.feature_selection import VarianceThreshold
from sklearn.feature_selection import SelectKBest, SelectPercentile
constant_filter = VarianceThreshold(threshold=0.01)
constant_filter.fit(X_train)
X_train_filter = constant_filter.transform(X_train)
X_test_filter = constant_filter.transform(X_test)

In [ ]:
X_train_T = X_train_filter.T
X_test_T = X_test_filter.T
X_train_T = pd.DataFrame(X_train_T)
X_test_T = pd.DataFrame(X_test_T)

In [ ]:
X_train_T.duplicated().sum()

0

In [ ]:
duplicated_features = X_train_T.duplicated()

In [ ]:
features_to_keep = [not index for index in duplicated_features]
X_train_unique = X_train_T[features_to_keep].T
X_test_unique = X_test_T[features_to_keep].T
X_train_unique.shape, X_test_unique.shape

((61, 7070), (16, 7070))

In [ ]:
#Function for KNN Classifier C1
from sklearn.neighbors import KNeighborsClassifier
def run_knn(X_train, X_test, y_train, y_test):
    c1 =KNeighborsClassifier(n_neighbors=3)
    c1.fit(X_train, y_train)
    y_pred = c1.predict(X_train)
    y_test_pred=c1.predict(X_test)
    print('Training 80% data report::')
    print('Accuracy Score: ')
    print(accuracy_score(y_train, y_pred))
    print('F1-Score: ')
    print(f1_score(y_train, y_pred))
    print('Confusion Matrix: ')
    print(confusion_matrix(y_train, y_pred))
    print('Testing 20% data report::')
    print('Accuracy Score: ')
    print(accuracy_score(y_test, y_test_pred))
    print('F1-Score: ')
    print(f1_score(y_test, y_test_pred))
    print('Confusion Matrix: ')
    print(confusion_matrix(y_test, y_test_pred))


In [ ]:
#Function for SVM Classifier C2
def run_svm(X_train, X_test, y_train, y_test):
    c2 =svm.SVC()
    c2.fit(X_train, y_train)
    y_pred = c2.predict(X_train)
    y_test_pred=c2.predict(X_test)
    print('Training 80% data report::')
    print('Accuracy Score: ')
    print(accuracy_score(y_train, y_pred))
    print('F1-Score: ')
    print(f1_score(y_train, y_pred))
    print('Confusion Matrix: ')
    print(confusion_matrix(y_train, y_pred))
    print('Testing 20% data report::')
    print('Accuracy Score: ')
    print(accuracy_score(y_test, y_test_pred))
    print('F1-Score: ')
    print(f1_score(y_test, y_test_pred))
    print('Confusion Matrix: ')
    print(confusion_matrix(y_test, y_test_pred))

## Classification without feature selection

In [ ]:
%%time
run_knn(X_train_unique, X_test_unique, y_train, y_test)

Training 80% data report::
Accuracy Score: 
0.9508196721311475
F1-Score: 
0.9655172413793104
Confusion Matrix: 
[[16  0]
 [ 3 42]]
Testing 20% data report::
Accuracy Score: 
0.875
F1-Score: 
0.9166666666666666
Confusion Matrix: 
[[ 3  0]
 [ 2 11]]
CPU times: user 296 ms, sys: 12 ms, total: 308 ms
Wall time: 316 ms


In [ ]:
%%time
run_svm(X_train_unique, X_test_unique, y_train, y_test)

Training 80% data report::
Accuracy Score: 
0.7704918032786885
F1-Score: 
0.8653846153846153
Confusion Matrix: 
[[ 2 14]
 [ 0 45]]
Testing 20% data report::
Accuracy Score: 
0.8125
F1-Score: 
0.896551724137931
Confusion Matrix: 
[[ 0  3]
 [ 0 13]]
CPU times: user 255 ms, sys: 7.04 ms, total: 262 ms
Wall time: 261 ms


## Functions of Mutual Information based feature selection(f1), F- Classifier(f2) and T-Test(f3)

In [ ]:
# Functions of Mutual information
def _compute_mi(x, y, n_neighbors=3):
        return mutual_info_score(x, y)

def _iterate_columns(X, columns=None):
    if columns is None:
        columns = range(X.shape[1])

    if issparse(X):
        for i in columns:
            x = np.zeros(X.shape[0])
            start_ptr, end_ptr = X.indptr[i], X.indptr[i + 1]
            x[X.indices[start_ptr:end_ptr]] = X.data[start_ptr:end_ptr]
            yield x
    else:
        for i in columns:
            yield X[:, i]


def _estimate_mi(X, y,n_neighbors=3):
    X, y = check_X_y(X, y, accept_sparse='csc')
    n_samples, n_features = X.shape
    discrete_features = issparse(X)
    discrete_mask = np.empty(n_features, dtype=bool)
    discrete_mask.fill(discrete_features)
    
    mi = [_compute_mi(x, y, n_neighbors) for
          x, discrete_feature in zip(_iterate_columns(X), discrete_mask)]

    return np.array(mi)

def mutual_info_classifier(X, y, n_neighbors=3,):
    check_classification_targets(y)
    return _estimate_mi(X, y, n_neighbors)

In [ ]:
#Functions for F classifier 
def f_oneway(*args):
    n_classes = len(args)
    args = [as_float_array(a) for a in args]
    n_samples_per_class = np.array([a.shape[0] for a in args])
    n_samples = np.sum(n_samples_per_class)
    ss_alldata = sum(safe_sqr(a).sum(axis=0) for a in args)
    sums_args = [np.asarray(a.sum(axis=0)) for a in args]
    square_of_sums_alldata = sum(sums_args) ** 2
    square_of_sums_args = [s ** 2 for s in sums_args]
    sstot = ss_alldata - square_of_sums_alldata / float(n_samples)
    ssbn = 0.
    for k, _ in enumerate(args):
        ssbn += square_of_sums_args[k] / n_samples_per_class[k]
    ssbn -= square_of_sums_alldata / float(n_samples)
    sswn = sstot - ssbn
    dfbn = n_classes - 1
    dfwn = n_samples - n_classes
    msb = ssbn / float(dfbn)
    msw = sswn / float(dfwn)
    constant_features_idx = np.where(msw == 0.)[0]
    f = msb / msw #High variance upon low variance 
    # flatten matrix to vector in sparse case
    f = np.asarray(f).ravel()
    prob = special.fdtrc(dfbn, dfwn, f)
    return f, prob


def f_classif(X, y):
    X, y = check_X_y(X, y, accept_sparse=['csr', 'csc', 'coo'])
    args = [X[safe_mask(X, y == k)] for k in np.unique(y)]
    return f_oneway(*args)

In [ ]:
#Functions for  t-test 
import math
def t_oneway(*args):
    n_classes = len(args)
    args = [as_float_array(a) for a in args]
    n_samples_per_class = np.array([a.shape[0] for a in args])
    n_samples = np.sum(n_samples_per_class)
    ss_alldata = sum(safe_sqr(a).sum(axis=0) for a in args)
    sums_args = [np.asarray(a.sum(axis=0)) for a in args]
    square_of_sums_alldata = sum(sums_args) ** 2
    square_of_sums_args = [s ** 2 for s in sums_args]
    sstot = ss_alldata - square_of_sums_alldata / float(n_samples)
    ssbn = 0.
    for k, _ in enumerate(args):
        ssbn += square_of_sums_args[k] / n_samples_per_class[k]
    ssbn -= square_of_sums_alldata / float(n_samples)
    sswn = sstot - ssbn
    dfbn = n_classes - 1
    dfwn = n_samples - n_classes
    msb = ssbn / float(dfbn)
    msw = sswn / float(dfwn)
    constant_features_idx = np.where(msw == 0.)[0]
    t = (ssbn-sswn)**2/ (msb+msw) #Taking sqrt of t value instead of absolute as t due to limitation of numpy. t^2= (absolute differences of means/sum of variances)^2
    # flatten matrix to vector in sparse case
    t = np.asarray(t).ravel()
    prob = special.fdtrc(dfbn, dfwn, t)
    return t, prob


def t_test(X, y):
    X, y = check_X_y(X, y, accept_sparse=['csr', 'csc', 'coo'])
    args = [X[safe_mask(X, y == k)] for k in np.unique(y)]
    return t_oneway(*args)

In [ ]:
mi = mutual_info_classifier(X_train_unique, y_train) 
len(mi)

7070

In [ ]:
mi = pd.Series(mi)
mi.index = X_train_unique.columns

In [ ]:
mi.sort_values(ascending=False, inplace = True)

In [ ]:
mi.index

Int64Index([6288, 1903, 1874, 4738, 4737, 4736, 4735, 1880, 4732, 1883,
            ...
            2619, 5443, 5395, 4517, 6802, 4356, 6630, 5148,  127, 4261],
           dtype='int64', length=7070)

### Task C.a: Cascading F1( N features ) → F2( 2N/3 features out of selected features from F1) → F3(N/3 features out of selected features from F2) then applying classifiers C1 and C2

### Selecting N Features of f1

In [ ]:
sel = SelectKBest(mutual_info_classifier, k=int(len(mi.index)*0.15)).fit(X_train_unique, y_train)#0.15 is multiplied to take total features les than 20%
X_train_unique.columns[sel.get_support()]

Int64Index([4038, 4040, 4041, 4044, 4053, 4054, 4056, 4057, 4060, 4061,
            ...
            7041, 7042, 7044, 7056, 7058, 7061, 7062, 7063, 7065, 7066],
           dtype='int64', length=1060)

In [ ]:
len(X_train_unique.columns[sel.get_support()])

1060

In [ ]:

X_train_mi = sel.transform(X_train_unique)
X_test_mi = sel.transform(X_test_unique)
X_train_mi.shape

(61, 1060)

### Selecting 2N/3 Features out of selected feature of f1 with f2

In [ ]:
fc= f_classif(X_train_mi, y_train) 
len(fc[0])

1060

In [ ]:
fc[: 10]

(array([0.21466848, 4.09357888, 1.05413006, ..., 8.44694431, 8.29195401,
        0.45188712]),
 array([0.64483729, 0.04758445, 0.30874885, ..., 0.00514272, 0.00554065,
        0.50406425]))

In [ ]:
fvalue_selector = SelectKBest(f_classif, k =int(2*len(fc[0])/3) )

In [ ]:
features_kbest = fvalue_selector.fit_transform(X_train_mi, y_train)

In [ ]:
X_train_fc = fvalue_selector.transform(X_train_mi)
X_test_fc = fvalue_selector.transform(X_test_mi)
X_train_fc.shape

(61, 706)

### Selecting N/3 features out of selected features from F2 with F3

In [ ]:
tt= t_test(X_train_fc, y_train) 
len(tt[0])
tt[: 10]
tvalue_selector = SelectKBest(t_test, k =int(len(tt[0])/3) )
featurestt_kbest = tvalue_selector.fit_transform(X_train_fc, y_train)
X_train_tt = tvalue_selector.transform(X_train_fc)
X_test_tt = tvalue_selector.transform(X_test_fc)
X_train_tt.shape

(61, 235)

### Application Of KNN (C1)

In [ ]:
%%time
run_knn(X_train_tt, X_test_tt, y_train, y_test)

Training 80% data report::
Accuracy Score: 
0.9836065573770492
F1-Score: 
0.9887640449438202
Confusion Matrix: 
[[16  0]
 [ 1 44]]
Testing 20% data report::
Accuracy Score: 
0.8125
F1-Score: 
0.8695652173913044
Confusion Matrix: 
[[ 3  0]
 [ 3 10]]
CPU times: user 24.5 ms, sys: 3.02 ms, total: 27.5 ms
Wall time: 25.2 ms


### Application Of SVM (C2)

In [ ]:
%%time
run_svm(X_train_tt, X_test_tt, y_train, y_test)

Training 80% data report::
Accuracy Score: 
0.9180327868852459
F1-Score: 
0.9473684210526316
Confusion Matrix: 
[[11  5]
 [ 0 45]]
Testing 20% data report::
Accuracy Score: 
0.9375
F1-Score: 
0.962962962962963
Confusion Matrix: 
[[ 2  1]
 [ 0 13]]
CPU times: user 22.8 ms, sys: 951 µs, total: 23.7 ms
Wall time: 24.5 ms


### Task C.b: F2 → F3 → F1 then applying classifiers C1 and C2

In [ ]:
fc= f_classif(X_train, y_train) 
fvalue_selector = SelectKBest(f_classif, k =int(len(fc[0])*0.15) )
features_kbest = fvalue_selector.fit_transform(X_train_unique, y_train)
X_train_fc = fvalue_selector.transform(X_train_unique)
X_test_fc = fvalue_selector.transform(X_test_unique)
X_train_fc.shape

(61, 1060)

In [ ]:
tt= t_test(X_train_fc, y_train) 
len(tt[0])
tt[: 10]
tvalue_selector = SelectKBest(t_test, k =int(2*len(tt[0])/3) )
featurestt_kbest = tvalue_selector.fit_transform(X_train_fc, y_train)
X_train_t = tvalue_selector.transform(X_train_fc)
X_test_t = tvalue_selector.transform(X_test_fc)
X_train_t.shape

(61, 706)

In [ ]:
mi = mutual_info_classifier(X_train_t, y_train) 
mi[:10]
mi = pd.Series(mi)

In [ ]:
mi.sort_values(ascending=False, inplace = True)
sel = SelectKBest(mutual_info_classifier, k=int(len(mi.index)/3)).fit(X_train_t, y_train)
X_train_mi = sel.transform(X_train_t)
X_test_mi = sel.transform(X_test_t)
X_train_mi.shape

(61, 235)

### Application Of KNN (C1)

In [ ]:
%%time
run_knn(X_train_mi, X_test_mi, y_train, y_test)

Training 80% data report::
Accuracy Score: 
0.9672131147540983
F1-Score: 
0.9772727272727273
Confusion Matrix: 
[[16  0]
 [ 2 43]]
Testing 20% data report::
Accuracy Score: 
0.9375
F1-Score: 
0.9600000000000001
Confusion Matrix: 
[[ 3  0]
 [ 1 12]]
CPU times: user 22.6 ms, sys: 4.93 ms, total: 27.5 ms
Wall time: 27.9 ms


### Application Of SVM (C2)

In [ ]:
%%time
run_svm(X_train_mi, X_test_mi, y_train, y_test)

Training 80% data report::
Accuracy Score: 
0.9180327868852459
F1-Score: 
0.945054945054945
Confusion Matrix: 
[[13  3]
 [ 2 43]]
Testing 20% data report::
Accuracy Score: 
0.9375
F1-Score: 
0.9600000000000001
Confusion Matrix: 
[[ 3  0]
 [ 1 12]]
CPU times: user 20.1 ms, sys: 1.97 ms, total: 22.1 ms
Wall time: 21.5 ms


### Task C.c: F3 → F1 → F2 then applying classifiers C1 and C2

In [ ]:
tt= t_test(X_train, y_train) 
len(tt[0])
tt[: 10]
tvalue_selector = SelectKBest(t_test, k =int(len(tt[0])*0.15) )
featurestt_kbest = tvalue_selector.fit_transform(X_train, y_train)
X_train_t = tvalue_selector.transform(X_train)
X_test_t = tvalue_selector.transform(X_test)
X_train_t.shape

(61, 1060)

In [ ]:
mi = mutual_info_classifier(X_train_t, y_train) 
mi = pd.Series(mi)
mi.sort_values(ascending=False, inplace = True)
sel = SelectKBest(mutual_info_classifier, k=int(2*len(mi.index)/3)).fit(X_train_t, y_train)
X_train_mi = sel.transform(X_train_t)
X_test_mi = sel.transform(X_test_t)
X_train_mi.shape

(61, 706)

In [ ]:
fc= f_classif(X_train_mi, y_train) 
fvalue_selector = SelectKBest(f_classif, k =int(len(fc[0])/3) )
features_kbest = fvalue_selector.fit_transform(X_train_mi, y_train)
X_train_fc = fvalue_selector.transform(X_train_mi)
X_test_fc = fvalue_selector.transform(X_test_mi)
X_train_fc.shape

(61, 235)

### Application Of KNN (C1)

In [ ]:
%%time
run_knn(X_train_fc, X_test_fc, y_train, y_test)

Training 80% data report::
Accuracy Score: 
0.9508196721311475
F1-Score: 
0.9655172413793104
Confusion Matrix: 
[[16  0]
 [ 3 42]]
Testing 20% data report::
Accuracy Score: 
0.9375
F1-Score: 
0.9600000000000001
Confusion Matrix: 
[[ 3  0]
 [ 1 12]]
CPU times: user 25.1 ms, sys: 3.11 ms, total: 28.2 ms
Wall time: 29.7 ms


### Application Of SVM (C2)

In [ ]:
%%time
run_svm(X_train_fc, X_test_fc, y_train, y_test)

Training 80% data report::
Accuracy Score: 
0.9836065573770492
F1-Score: 
0.9887640449438202
Confusion Matrix: 
[[16  0]
 [ 1 44]]
Testing 20% data report::
Accuracy Score: 
0.9375
F1-Score: 
0.962962962962963
Confusion Matrix: 
[[ 2  1]
 [ 0 13]]
CPU times: user 19.4 ms, sys: 2.98 ms, total: 22.3 ms
Wall time: 23.3 ms


### End of Task C